let fullName = "T. A. Nafiz";
let age = 20;
let country = "Bangladesh";
let favoriteLanguage = "JavaScript";
let dreamJob = "Full-Stack Developer";
let yearsToGoal = 1;
let isLearning = true;

console.log("==============================");
console.log("         MY PROFILE");
console.log("==============================");
console.log();
console.log("Name: " + fullName);
console.log("Age: " + age);
console.log("Country: " + country);
console.log("Favorite Language: " + favoriteLanguage);
console.log("Dream Job: " + dreamJob);
console.log("Years to Reach Goal: " + yearsToGoal);
console.log("Learning JavaScript: " + isLearning);
console.log();
console.log("==============================");